### ISSUE TITLE
Add custom icons for features

### ISSUE THREAD

**Issue by nvasquedr** [Apt3kStudio/Watch#12]
# Feature icons 

Add icon for each functionality on the watch. Make sure the icons are appropriately sized to fit the buttons they will be added to. 

## Requirement 
- [x] [Vibrate Icon](https://drive.google.com/open?id=1GH0MMzeBpZSlOSTdzYEk5FFyCP9dXEQF)

- [x] [Sound Icon](https://drive.google.com/open?id=16R5J6tCLvSGF99FOa22ZlW2seRlCRaZd)

- [x] [Flash Icon](https://drive.google.com/open?id=1FUr5tnW3opCYlnV-ryZk2FaI5-2duJJ-)

**Comment by jagomez16** [comment]
Link to main features: 

1. [Vibrate Icon](https://drive.google.com/open?id=1GH0MMzeBpZSlOSTdzYEk5FFyCP9dXEQF)

2. [Sound Icon](https://drive.google.com/open?id=16R5J6tCLvSGF99FOa22ZlW2seRlCRaZd)

3. [Flash Icon](https://drive.google.com/open?id=1FUr5tnW3opCYlnV-ryZk2FaI5-2duJJ-)
