### ISSUE TITLE
Why developers do not have access to the low-level Bluetooth communication?

### ISSUE THREAD

**Issue by jagomez16** [Apt3kStudio/Watch#2]
### **Wearable Runtime & Connectivity Architectures**

Here is what Google found out when they analyzed phone and wearable usage.

![image](https://user-images.githubusercontent.com/44250046/47260254-b8256f00-d485-11e8-8dbf-35970369bb41.png)

The main idea behind this research is that _**it is a lot easier to engage with content when it is on your wrist**_. **You are way more focused when engaging with it**, and you are no that easily distracted. The **screen is so small that it is just physically inconvenient to scroll text on a wrist**. And sometimes there’s no screen at all.

**Google Smart Accessories Era**
![image](https://user-images.githubusercontent.com/44250046/47260284-9d072f00-d486-11e8-9311-6d6674a7eacc.png)

In summer, Google finally announced their watches. All of them are based on a specific version of Android OS: Android Wear. This means that your watch runs real Android OS: you have Linux, on top of it you have stripped Android and on top of that you have VMs running your apps. So many abstraction layers.

Right now Android Wear devices use Bluetooth for communication. **_As a developer, you have no access to the low-level bluetooth communication_**. You work on a higher level of abstraction, called Android Wear SDK. It consists of several crucial parts: Nodes API (detects devices in the wearable network), Message API (allows sending messages between nodes) and Data API (allows data synchronisation between nodes). **No direct connection to the Internet is available for you**. So, when you’ll need to show some pictures of kittens on a wrist, you’ll use Data API to send assets from the companion app to the watch.

Sources: https://labs.eleks.com/2014/11/wearable-runtime-connectivity-architectures.html

### **Questions / Concerns:**

1. No direct connection to the Internet is available for you?
- Because the watch is directly connected to the phone via Bluetooth instead of the watch being connected to an internet contention router and then to the phone

2. **Why developers do not have access to the low-level Bluetooth communication?**

   - [ ] **Bluetooth Vs. Bluetooth Low Energy: What's The Difference?** In summary, Bluetooth and Bluetooth Low Energy are used for very different purposes. Bluetooth can handle a lot of data, but consumes battery life quickly and costs a lot more. BLE is used for applications that do not need to exchange large amounts of data, and can therefore run on battery power for years at a cheaper cost. It all depends on what you’re trying to accomplish.

     Sources: https://www.link-labs.com/blog/bluetooth-vs-bluetooth-low-energy

**Comment by dioscarr** [comment]
This needs to be move to the wiki page
